## NumPy Library 

NumPy - NumPy is a Python library used for working with arrays.
-   Numerical Python
-   Arrays in Python
-   homogeneous - Same type of values can store
-   In Python we have lists that serve the purpose of arrays, but they are slow to process.
-   NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
-   The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
-   Arrays are very frequently used in data science, where speed and resources are very important.

In [1]:
# import numpy
import numpy as np

-  #### NumPy Arrays

Creating Arrays
-  1D array 
-  2D array
-  3D array

In [108]:
# 1D array 
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
type(a)

numpy.ndarray

In [19]:
a.ndim

1

In [ ]:
# 2D array 
b = np.array([[2,3,4],[4,5,6]])
b

In [14]:
type(b)

numpy.ndarray

In [20]:
b.ndim

2

In [17]:
# 3D array 
c = np.array([[[4,5,6],[9,5,30],[7,2,6]]])
c

array([[[ 4,  5,  6],
        [ 9,  5, 30],
        [ 7,  2,  6]]])

In [18]:
type(c)

numpy.ndarray

In [21]:
c.ndim

3

-  #### Initial Placeholders

Create an array of zeros 
-  np.zeros((r,c))

In [42]:
# by default, np.zeros() creates an array of floating-point numbers with dtype='float64'.
# np.zeros() accepts any sequence-like object (like a tuple or list) to specify the shape.
# So both (3, 4) and [3, 4] are interpreted as shape (3, 4).
zero_array = np.zeros([3,4])
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
zero_array.dtype

dtype('float64')

In [40]:
zero_array.ndim

2

In [51]:
array = np.zeros(([6]))
array

array([0., 0., 0., 0., 0., 0.])

In [52]:
array.ndim

1

Create an array of ones

In [37]:
one_array = np.ones([5,4])
one_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
one_array.ndim

2

In [38]:
one_array.dtype

dtype('float64')

Create an array of evenly

In [60]:
# np.ones((no. of array,r,c))
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

spaced values (step value) 

In [73]:
# np.arange(start no. , end no. , spacing)
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

spaced values (number of samples)

In [78]:
# np.linspace(star value,end value, no of values we can from start to end)
np.linspace(5,55,10)

array([ 5.        , 10.55555556, 16.11111111, 21.66666667, 27.22222222,
       32.77777778, 38.33333333, 43.88888889, 49.44444444, 55.        ])

Create a constant array

In [83]:
# np.full((r,c),no whch we want to fill in array)
np.full((4,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

Create a 2X2 identity matrix

In [85]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Create an array with random values

In [93]:
# Creating a array of random values with r and c between 0 to 1 
np.random.random((3,3))

array([[0.30654282, 0.14761299, 0.36840463],
       [0.23027992, 0.98202786, 0.68138738],
       [0.47649438, 0.58363917, 0.87406071]])

Create an empty array

In [99]:
np.empty((3,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 6.23058707e-307],
       [2.22526399e-307, 2.05837348e-312]])

-  #### I/O

Saving & Loading On Disk

In [109]:
# np.save('name which we want to give', array which we want to save )
np.save('my_array',a)

In [111]:
# np.load('name of array which we want to load.npy')
np.load('my_array.npy')

array([1, 2, 3, 4, 5])

In [116]:
# 'array.npz': the filename (you can omit .npz and it will be added automatically)
# a, b: the NumPy arrays we want to save
zip_arr = np.savez('array.npz',a,b)

In [122]:
# To load them back:
zip_arr = np.load('array.npz')
zip_arr.files

['arr_0', 'arr_1']

In [125]:
zip_arr['arr_0']

array([1, 2, 3, 4, 5])

In [126]:
zip_arr['arr_1']

array([[2, 3, 4],
       [4, 5, 6]])

Saving & Loading Text Files

In [139]:
#np.loadtxt("file name which you want to load.txt")
# File and jnb should be in same folder 
np.loadtxt("sample_array.txt")

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [140]:
np.savetxt('sample_array',a,delimiter = " + ")

In [144]:
loaded_a = np.loadtxt('sample_array.txt', delimiter=" ")
loaded_a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

-  #### Data Types

In [149]:
# Signed 64-bit integer types
np.int64 

numpy.int64

In [150]:
# Standard double-precision floating point
np.float32 

numpy.float32

In [152]:
# Complex numbers represented by 128 floats
# NumPy's complex number with 128-bit precision
np.complex128

numpy.complex128

In [154]:
#  Boolean type storing TRUE and FALSE values
np.bool_

numpy.bool_

In [156]:
# Python object type
np.object_

numpy.object_

In [157]:
# Fixed-length string type
np.string_ 

numpy.bytes_

In [158]:
# Fixed-length unicode type
np.unicode_ 

numpy.str_

-  #### Inspecting Your Array

In [161]:
b

array([[2, 3, 4],
       [4, 5, 6]])

In [162]:
# Array dimensions
b.shape

(2, 3)

In [167]:
c

array([[[ 4,  5,  6],
        [ 9,  5, 30],
        [ 7,  2,  6]]])

In [166]:
# Length of array
len(c)

1

In [168]:
# Number of array elements
c.size

9

In [169]:
# Number of array dimensions
c.ndim

3

In [170]:
# Data type of array elements
c.dtype

dtype('int32')

In [171]:
# Name of data type
c.dtype.name

'int32'

In [182]:
# Convert an array to a different type
b.astype(float) 

array([[2., 3., 4.],
       [4., 5., 6.]])

In [183]:
b.astype(str)

array([['2', '3', '4'],
       ['4', '5', '6']], dtype='<U11')

-  #### Asking for Help 

In [188]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


-  #### Array Mathematics

Arithmetic Operations

In [197]:
a1 = np.arange(2,20,4)
a1

array([ 2,  6, 10, 14, 18])

In [196]:
b1 = np.arange(3,60,12)
b1

array([ 3, 15, 27, 39, 51])

In [201]:
# Subtraction
b1 - a1

array([ 1,  9, 17, 25, 33])

In [203]:
np.subtract(b1,a1)

array([ 1,  9, 17, 25, 33])

In [204]:
# Addition
b1 + a1

array([ 5, 21, 37, 53, 69])

In [205]:
np.add(b1,a1)

array([ 5, 21, 37, 53, 69])

In [208]:
# Division
b1/a1

array([1.5       , 2.5       , 2.7       , 2.78571429, 2.83333333])

In [207]:
np.divide(b1,a1)

array([1.5       , 2.5       , 2.7       , 2.78571429, 2.83333333])

In [209]:
# Multiplication
a1 * b1

array([  6,  90, 270, 546, 918])

In [210]:
np.multiply(a1,b1)

array([  6,  90, 270, 546, 918])

In [214]:
# Exponentiation
np.exp(b)

array([[  7.3890561 ,  20.08553692,  54.59815003],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [215]:
# Square root
np.sqrt(b1)

array([1.73205081, 3.87298335, 5.19615242, 6.244998  , 7.14142843])

In [217]:
# Print sines of an array
np.sin(a1)

array([ 0.90929743, -0.2794155 , -0.54402111,  0.99060736, -0.75098725])

In [218]:
# Element-wise cosine 
np.cos(a1)

array([-0.41614684,  0.96017029, -0.83907153,  0.13673722,  0.66031671])

In [219]:
# Element-wise natural logarithm 
np.log(b1)

array([1.09861229, 2.7080502 , 3.29583687, 3.66356165, 3.93182563])

In [221]:
# Dot product
a1.dot(b1)

1830

In [222]:
import numpy as np

a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])

result = a1.dot(b1)
print(result)  # Output: 32
# (1×4)+(2×5)+(3×6)
#  = 04+10+18=32


32


Comparison

In [228]:
a1

array([1, 2, 3])

In [229]:
b1

array([4, 5, 6])

In [227]:
# Element-wise comparison
a1 == b1

array([False, False, False])

In [231]:
a2 = np.array((8,9,0))
b2 = np.array((8,9,0))
a2 == b2

array([ True,  True,  True])

In [232]:
# Element-wise comparison
a2< b2 

array([False, False, False])

In [234]:
b1>b2

array([False, False,  True])

In [235]:
# Array-wise comparison
np.array_equal(a1,b1)

False

In [236]:
np.array_equal(a2,b2)

True

Aggregate Functions

In [237]:
# Array-wise sum
a1.sum()

6

In [239]:
# Array-wise minimum value
b1.min()

4

In [241]:
# Maximum value of an array row
b1.max(axis = 0)

6

In [244]:
# Cumulative sum of the elements
b1.cumsum

<function ndarray.cumsum>

In [247]:
# mean
a1.mean()

2.0

In [251]:
# This happens because median() is not a method of a NumPy array object. Instead, it's a function in the NumPy module.
np.median(b1)


5.0

In [256]:
# Correlation coefficient
np.corrcoef(a1)

1.0

In [257]:
# Standard deviation
np.std(b1)

0.816496580927726

-  #### Copying Array

In [260]:
# Create a view of the array with the same data
v = a1.view()
v

array([1, 2, 3])

In [262]:
# Create a copy of the array
np.copy(b1)

array([4, 5, 6])

In [267]:
# Create a deep copy of the array
s = b1.copy()
s

array([4, 5, 6])

-  #### Sorting Arrays

In NumPy, the axis argument tells the function along which axis to perform the operation.

axis=0 → operate column-wise (i.e., sort each column individually).

axis=1 → operate row-wise (i.e., sort each row individually).

In [276]:
# Sort an array
arr = np.array((6,5,4,2,5,2,2,2,5,7,8,9,999,9,5,22,1,4,545534,5,0,4))
arr.sort()
arr

array([     0,      1,      2,      2,      2,      2,      4,      4,
            4,      5,      5,      5,      5,      5,      6,      7,
            8,      9,      9,     22,    999, 545534])

In [275]:
# Sort the elements of an array's axis
arr.sort(axis=0)
arr

array([     1,      2,      2,      2,      2,      4,      4,      4,
            5,      5,      5,      5,      5,      6,      7,      8,
            9,      9,     22,    999, 545534])

-  #### Subsetting, Slicing, Indexing

Subsetting

In [280]:
# Select the element at the 3rd index
array = np.array([2,3,6,7,9,0,5])
array[3]

7

In [286]:
# select the element at row 1 column 2
#  6.0 (equivalent to b[1][2])
b

array([[2, 3, 4],
       [4, 5, 6]])

In [289]:
b[1,2]

6

Slicing

In [291]:
array

array([2, 3, 6, 7, 9, 0, 5])

In [293]:
# Select items
array[1:5]

array([3, 6, 7, 9])

In [295]:
array[0::2]

array([2, 6, 9, 5])

In [296]:
array[0::]

array([2, 3, 6, 7, 9, 0, 5])

In [297]:
# Reversed array 
array[::-1]

array([5, 0, 9, 7, 6, 3, 2])

In [298]:
array[:-1:]

array([2, 3, 6, 7, 9, 0])

In [303]:
# Boolean Indexing
array[array > 6]

array([7, 9])

Fancy Indexing

In [310]:
b

array([[2, 3, 4],
       [4, 5, 6]])

In [308]:
# Select a subset of the matrix’s rows and coulmns
b[[1, 0, 1, 0],[0, 1, 2, 0]] 

array([4, 3, 6, 2])

-  ##### Array Manipulation

Transposing Array

In [313]:
# Permute array dimensions
# convert row to col , col to row
i = np.transpose(b)
i

array([[2, 4],
       [3, 5],
       [4, 6]])

In [314]:
i.T

array([[2, 3, 4],
       [4, 5, 6]])

Changing Array Shape


In [315]:
# Flatten the array
b.ravel()

array([2, 3, 4, 4, 5, 6])

In [321]:
# Reshape, but don’t change data
b.reshape(3,2)

array([[2, 3],
       [4, 4],
       [5, 6]])

Adding/Removing Elements


In [327]:
# Return a new array with shape (2,6)
h = np.arange(5,55,5)
h.resize((2,6))

In [328]:
h

array([[ 5, 10, 15, 20, 25, 30],
       [35, 40, 45, 50,  0,  0]])

In [329]:
# Append items to an array
np.append(h,b)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50,  0,  0,  2,  3,  4,  4,  5,
        6])

In [330]:
b

array([[2, 3, 4],
       [4, 5, 6]])

In [332]:
# Insert items in an array
#np.inser(array,index postion where we want to place value, value which we want to place)
# it will add extra index 
np.insert(h,1,6)

array([ 5,  6, 10, 15, 20, 25, 30, 35, 40, 45, 50,  0,  0])

In [338]:
# Delete items from an array
np.delete(h,[6])

array([ 5, 10, 15, 20, 25, 30, 40, 45, 50,  0,  0])

Combining Arrays

In [348]:
x = np.array([[6,7,8,9],[2,3,4,5]])
x

array([[6, 7, 8, 9],
       [2, 3, 4, 5]])

In [349]:
y = np.array([[26,17,28,79],[20,31,45,55]])
y

array([[26, 17, 28, 79],
       [20, 31, 45, 55]])

In [351]:
#  Concatenate arrays
np.concatenate((x,y))

array([[ 6,  7,  8,  9],
       [ 2,  3,  4,  5],
       [26, 17, 28, 79],
       [20, 31, 45, 55]])

In [353]:
# Stack arrays vertically (row-wise)
np.stack((x,y))

array([[[ 6,  7,  8,  9],
        [ 2,  3,  4,  5]],

       [[26, 17, 28, 79],
        [20, 31, 45, 55]]])

In [354]:
# Stack arrays vertically (row-wise)
np.vstack((x,y))

array([[ 6,  7,  8,  9],
       [ 2,  3,  4,  5],
       [26, 17, 28, 79],
       [20, 31, 45, 55]])

In [355]:
# Stack arrays horizontally (column-wise)
np.hstack((x,y))

array([[ 6,  7,  8,  9, 26, 17, 28, 79],
       [ 2,  3,  4,  5, 20, 31, 45, 55]])

In [356]:
 np.r_[x,y] 

array([[ 6,  7,  8,  9],
       [ 2,  3,  4,  5],
       [26, 17, 28, 79],
       [20, 31, 45, 55]])

In [357]:
# Create stacked column-wise arrays
np.column_stack((x,y)) 

array([[ 6,  7,  8,  9, 26, 17, 28, 79],
       [ 2,  3,  4,  5, 20, 31, 45, 55]])

In [358]:
# Create stacked column-wise arrays
np.c_[x,y]

array([[ 6,  7,  8,  9, 26, 17, 28, 79],
       [ 2,  3,  4,  5, 20, 31, 45, 55]])

Splitting Arrays

In [360]:
# Split the array horizontally at the 2rd index
np.hsplit(x,2)

[array([[6, 7],
        [2, 3]]),
 array([[8, 9],
        [4, 5]])]

In [361]:
x

array([[6, 7, 8, 9],
       [2, 3, 4, 5]])

In [362]:
# Split the array vertically at the 2nd index
np.vsplit(y,2) 

[array([[26, 17, 28, 79]]), array([[20, 31, 45, 55]])]

In [363]:
y

array([[26, 17, 28, 79],
       [20, 31, 45, 55]])